In [1]:
import pandas as pd
import numpy as np
from datetime import datetime,timedelta
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")

df=pd.read_csv("./data/atp_data.csv",low_memory=False)
df.Date = df.Date.apply(lambda x:datetime.strptime(x, '%Y-%m-%d'))

In [24]:
df.loc[(df.Date.dt.year >= 2004) & (df.Date.dt.year <= 2020)]

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,Wsets,Lsets,Comment,PSW,PSL,B365W,B365L,elo_winner,elo_loser,proba_elo
5824,2,Chennai,TATA Open,2004-01-05,International,Outdoor,Hard,1st Round,3.0,Ferrer D.,...,2.0,1.0,Completed,1.885,1.971,1.727,2.000,1532.442364,1491.659048,0.558424
5825,3,Doha,Qatar Exxon Mobil Open,2004-01-05,International,Outdoor,Hard,1st Round,3.0,Youzhny M.,...,2.0,0.0,Completed,3.250,1.385,2.875,1.364,1575.119952,1792.533433,0.222435
5826,3,Doha,Qatar Exxon Mobil Open,2004-01-05,International,Outdoor,Hard,1st Round,3.0,Sargsian S.,...,2.0,1.0,Completed,1.746,2.180,1.571,2.250,1632.348147,1575.757760,0.580727
5827,3,Doha,Qatar Exxon Mobil Open,2004-01-05,International,Outdoor,Hard,1st Round,3.0,Heuberger I.,...,2.0,0.0,Completed,NaN,NaN,NaN,NaN,1412.825236,1488.233124,0.393152
5828,2,Chennai,TATA Open,2004-01-05,International,Outdoor,Hard,1st Round,3.0,Lisnard J.R.,...,2.0,0.0,Completed,1.562,2.580,1.571,2.250,1526.838130,1504.256603,0.532452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50353,32,London,Masters Cup,2020-11-20,Masters Cup,Indoor,Hard,Round Robin,3.0,Djokovic N.,...,2.0,0.0,Completed,1.320,3.780,1.330,3.250,2136.840159,1967.882134,0.725638
50354,32,London,Masters Cup,2020-11-20,Masters Cup,Indoor,Hard,Round Robin,3.0,Medvedev D.,...,2.0,0.0,Completed,1.300,3.960,1.250,3.750,1989.011618,1852.375235,0.687088
50355,32,London,Masters Cup,2020-11-21,Masters Cup,Indoor,Hard,Semifinals,3.0,Thiem D.,...,2.0,1.0,Completed,2.700,1.540,2.250,1.570,2020.504691,2145.619758,0.327344
50356,32,London,Masters Cup,2020-11-21,Masters Cup,Indoor,Hard,Semifinals,3.0,Medvedev D.,...,2.0,1.0,Completed,1.880,2.040,1.750,2.000,1999.024789,2152.635559,0.292297
50357,32,London,Masters Cup,2020-11-22,Masters Cup,Indoor,Hard,The Final,3.0,Medvedev D.,...,2.0,1.0,Completed,1.660,2.400,1.660,2.200,2021.671289,2042.029667,0.470735

In [2]:
df = df.loc[(df.Date.dt.year >= 2004) & (df.Date.dt.year <= 2020)]
losers = df['Loser'].unique()
winners = df['Winner'].unique()
players = np.concatenate([losers,winners])
players = np.unique(players)

players_total_play = []
players_wins = []
players_loses = []
players_odds = []

for player in players : 
    players_total_play.append(len(df.loc[df['Winner']==player]) + len(df.loc[df['Loser']==player]))
    players_wins.append(len(df.loc[df['Winner']==player]))
    players_loses.append(len(df.loc[df['Loser']==player]))
    players_odds.append((df.loc[df['Winner']==player].B365W.mean() + df.loc[df['Loser']==player].B365L.mean())/2)


d = {'player': players, 
     'games': players_total_play, 
     'wins':players_wins, 
     'loses':players_loses,
     'players_odds':players_odds}
df_players = pd.DataFrame(data=d)
df_players["ratio_win"] = df_players["wins"]/df_players["games"]

In [48]:
#.WRank

df.loc[df.Winner == "Federer R."].iloc[-1]

df.loc[df.Loser == "Federer R."].iloc[-1]

ATP                            36
Location                   London
Tournament              Wimbledon
Date          2021-07-07 00:00:00
Series                 Grand Slam
Court                     Outdoor
Surface                     Grass
Round               Quarterfinals
Best of                       5.0
Winner                 Hurkacz H.
Loser                  Federer R.
WRank                          18
LRank                           8
Wsets                         3.0
Lsets                         0.0
Comment                 Completed
PSW                          2.96
PSL                          1.46
B365W                         3.0
B365L                         1.4
elo_winner            1741.652912
elo_loser             2025.214347
proba_elo                0.163514
Name: 51891, dtype: object

In [66]:
df_players

                  player  games  wins  loses  players_odds  ratio_win
0               Hajek J.      2     1      1      2.915000   0.500000
1             Abdulla M.      1     0      1           NaN   0.000000
2                Abel M.      7     2      5      3.735200   0.285714
3             Acasuso J.    321   160    161      2.392554   0.498442
4          Adaktusson J.      1     0      1           NaN   0.000000
...                  ...    ...   ...    ...           ...        ...
1595      di Pasquale A.     37     9     28      2.719500   0.243243
1596     van Gemerden M.     10     4      6      3.455000   0.400000
1597       van Lottum J.     44    13     31      2.904973   0.295455
1598  van Scheppingen D.     41    14     27      2.950689   0.341463
1599     van der Meer N.      1     0      1           NaN   0.000000

[1600 rows x 6 columns]

In [75]:
df_players = pd.read_csv("./data/players.csv")
df_players.name

0                 Hajek J.
1               Abdulla M.
2                  Abel M.
3               Acasuso J.
4            Adaktusson J.
               ...
1285        di Pasquale A.
1286       van Gemerden M.
1287         van Lottum J.
1288    van Scheppingen D.
1289       van der Meer N.
Name: name, Length: 1290, dtype: object

In [97]:
import math 
training_matches=[]
df = df.head()

player1_name=[]
player1_ATPRank=[]
player1_game=[]
player1_wins=[]
player1_loses=[]

player2_name=[]
player2_ATPRank=[]
player2_game=[]
player2_wins=[]
player2_loses=[]

winner_player1=[]

for index, row in df.iterrows():
    player1 = df_players.loc[df_players.name == row.Winner]
    player2 = df_players.loc[df_players.name == row.Loser]
    if player1.size!=0:
        player1_name.append(player1.iloc[0]["name"])
    else:
        player1_name.append(math.nan)

    if player2.size!=0:
        player2_name.append(player2.iloc[0]["name"])
    else:
        player2_name.append(math.nan)


    winner_player1.append(1)
d = {
    'player1_name': player1_name, 
    'player2_name' : player2_name,
    'winner_player1' : winner_player1}

training_matches = pd.DataFrame(data=d)
    
training_matches

     player1_name    player2_name
0      Clement A.             NaN
1             NaN             NaN
2             NaN  Sanguinetti D.
3       Escude N.   El Aynaoui Y.
4  di Pasquale A.     Zabaleta M.